# Generated by Django 4.2.19 on 2025-03-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_from', models.CharField(max_length=3)),
                ('code_to', models.CharField(max_length=3)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('fare', models.CharField(max_length=10)),
                ('flight_no', models.CharField(max_length=10)),
                ('aircraft_name', models.CharField(max_length=30)),
                ('airline_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_from', models.CharField(max_length=3)),
                ('code_to', models.CharField(max_length=3)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('first_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_leg', to='search.legresult')),
                ('forth_leg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forth_leg', to='search.legresult')),
                ('second_leg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_leg', to='search.legresult')),
                ('third_leg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_leg', to='search.legresult')),
            ],
        ),
    ]
