# Generated by Django 4.2.19 on 2025-03-03 22:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_from', models.CharField(max_length=3)),
                ('name_to', models.CharField(max_length=3)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('flight_no', models.CharField(max_length=10)),
                ('airline_name', models.CharField(max_length=40)),
                ('fetch_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('fare', models.CharField(max_length=10)),
                ('fetch_time', models.DateTimeField(default=datetime.datetime.now)),
                ('first_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_leg', to='search.legcache')),
                ('forth_leg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forth_leg', to='search.legcache')),
                ('second_leg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_leg', to='search.legcache')),
                ('third_leg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_leg', to='search.legcache')),
            ],
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='first_leg',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='forth_leg',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='second_leg',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='third_leg',
        ),
        migrations.DeleteModel(
            name='LegResult',
        ),
        migrations.DeleteModel(
            name='SearchResult',
        ),
    ]
