# Generated by Django 4.2.19 on 2025-03-08 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miles', '0002_rename_fare_class_miles_is_economy'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchcache',
            name='miles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miles_info', to='miles.miles'),
        ),
    ]
