# Generated by Django 4.2.19 on 2025-03-03 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_legcache_searchcache_remove_searchresult_first_leg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchcache',
            old_name='forth_leg',
            new_name='fourth_leg',
        ),
    ]
