# Generated by Django 4.2.19 on 2025-03-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchcache_miles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchcache',
            old_name='code_from',
            new_name='name_from',
        ),
        migrations.RenameField(
            model_name='searchcache',
            old_name='code_to',
            new_name='name_to',
        ),
    ]
