# Generated by Django 4.2.19 on 2025-03-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_rename_code_from_searchcache_name_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcache',
            name='name_from',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='searchcache',
            name='name_to',
            field=models.CharField(max_length=50),
        ),
    ]
