# Generated by Django 4.2.19 on 2025-03-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_searchcache_name_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcache',
            name='fare',
            field=models.CharField(max_length=50),
        ),
    ]
