# Generated by Django 4.2.19 on 2025-03-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_searchcache_fare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchcache',
            name='miles',
        ),
        migrations.AddField(
            model_name='searchcache',
            name='miles_rate',
            field=models.FloatField(null=True, verbose_name=0),
        ),
    ]
