# Generated by Django 4.2.19 on 2025-03-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_remove_searchcache_miles_searchcache_miles_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcache',
            name='fare',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='searchcache',
            name='name_from',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='searchcache',
            name='name_to',
            field=models.CharField(max_length=100),
        ),
    ]
