# Generated by Django 4.2.19 on 2025-03-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_tg_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_chat_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
