# Generated by Django 4.2.19 on 2025-03-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_tg_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_period',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
