# Generated by Django 4.2.19 on 2025-03-04 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_from', models.CharField(max_length=3)),
                ('code_to', models.CharField(max_length=3)),
                ('fare_class', models.BooleanField()),
                ('fare_name', models.CharField(max_length=50)),
                ('fares_codes', models.JSONField()),
                ('miles_price', models.IntegerField()),
                ('fetch_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
