# Generated by Django 4.2.19 on 2025-03-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miles',
            old_name='fare_class',
            new_name='is_economy',
        ),
    ]
